### ISSUE TITLE
cannot build default `package`

### ISSUE THREAD

**Issue by ratson** [nix-community/flakelight#10]
Given https://github.com/ratson/bug-report/blob/flakelight-package/flake.nix

```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    flakelight.url = "github:nix-community/flakelight";
    flakelight.inputs.nixpkgs.follows = "nixpkgs";
  };
  outputs = { flakelight, ... }@inputs:
    flakelight ./. {
      inherit inputs;
      package = pkgs: pkgs.hello;
    };
}
```

Run `nix run github:ratson/bug-report/flakelight-package` results an error instead of printing `Hello, world!`

`nix flake show github:ratson/bug-report/flakelight-package` is giving `error: 'checks.aarch64-linux' is not an attribute set` too.

**Comment by accelbread** [comment]
Thanks for the report!

Seems that case was missed in the tests.

I've fixed it and added the corresponding tests here: 26a8a4454af4872ce7b4a76785e14d273219b12c...787ce03070c1d5c95f6700ab02972e498d0745f9.
